# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import message_service_pb2 as message__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in message_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StockManagement = channel.unary_unary(
                '/message.MessageService/StockManagement',
                request_serializer=message__service__pb2.StockRequest.SerializeToString,
                response_deserializer=message__service__pb2.StockResponse.FromString,
                _registered_method=True)
        self.GenerateUUID = channel.unary_unary(
                '/message.MessageService/GenerateUUID',
                request_serializer=message__service__pb2.UUIDRequest.SerializeToString,
                response_deserializer=message__service__pb2.UUIDResponse.FromString,
                _registered_method=True)
        self.ReverseString = channel.unary_unary(
                '/message.MessageService/ReverseString',
                request_serializer=message__service__pb2.ReverseRequest.SerializeToString,
                response_deserializer=message__service__pb2.ReverseResponse.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StockManagement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateUUID(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReverseString(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StockManagement': grpc.unary_unary_rpc_method_handler(
                    servicer.StockManagement,
                    request_deserializer=message__service__pb2.StockRequest.FromString,
                    response_serializer=message__service__pb2.StockResponse.SerializeToString,
            ),
            'GenerateUUID': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateUUID,
                    request_deserializer=message__service__pb2.UUIDRequest.FromString,
                    response_serializer=message__service__pb2.UUIDResponse.SerializeToString,
            ),
            'ReverseString': grpc.unary_unary_rpc_method_handler(
                    servicer.ReverseString,
                    request_deserializer=message__service__pb2.ReverseRequest.FromString,
                    response_serializer=message__service__pb2.ReverseResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'message.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('message.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StockManagement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageService/StockManagement',
            message__service__pb2.StockRequest.SerializeToString,
            message__service__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateUUID(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageService/GenerateUUID',
            message__service__pb2.UUIDRequest.SerializeToString,
            message__service__pb2.UUIDResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReverseString(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/message.MessageService/ReverseString',
            message__service__pb2.ReverseRequest.SerializeToString,
            message__service__pb2.ReverseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
