# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'message_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15message_service.proto\x12\x07message\"9\n\x0cStockRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x15\n\rsold_quantity\x18\x02 \x01(\x05\"+\n\rStockResponse\x12\x1a\n\x12remaining_quantity\x18\x01 \x01(\x05\"\x1f\n\x0bUUIDRequest\x12\x10\n\x08\x61ny_text\x18\x01 \x01(\t\"\x1c\n\x0cUUIDResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"\'\n\x0eReverseRequest\x12\x15\n\roriginal_text\x18\x01 \x01(\t\"(\n\x0fReverseResponse\x12\x15\n\rreversed_text\x18\x01 \x01(\t2\xd3\x01\n\x0eMessageService\x12@\n\x0fStockManagement\x12\x15.message.StockRequest\x1a\x16.message.StockResponse\x12;\n\x0cGenerateUUID\x12\x14.message.UUIDRequest\x1a\x15.message.UUIDResponse\x12\x42\n\rReverseString\x12\x17.message.ReverseRequest\x1a\x18.message.ReverseResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOCKREQUEST']._serialized_start=34
  _globals['_STOCKREQUEST']._serialized_end=91
  _globals['_STOCKRESPONSE']._serialized_start=93
  _globals['_STOCKRESPONSE']._serialized_end=136
  _globals['_UUIDREQUEST']._serialized_start=138
  _globals['_UUIDREQUEST']._serialized_end=169
  _globals['_UUIDRESPONSE']._serialized_start=171
  _globals['_UUIDRESPONSE']._serialized_end=199
  _globals['_REVERSEREQUEST']._serialized_start=201
  _globals['_REVERSEREQUEST']._serialized_end=240
  _globals['_REVERSERESPONSE']._serialized_start=242
  _globals['_REVERSERESPONSE']._serialized_end=282
  _globals['_MESSAGESERVICE']._serialized_start=285
  _globals['_MESSAGESERVICE']._serialized_end=496
# @@protoc_insertion_point(module_scope)
